import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "../apollo-client";
import { Button, Table, Image, Space, Popover } from "antd"
import moment from 'moment';
import { AiFillEye, AiOutlineArrowUp, AiOutlineArrowDown } from "react-icons/ai";
import { parse } from 'graphql';



export default function Home(props) {




    useEffect(() => {
        console.log("hello world")
    }, [])





    return (
        <div className={styles.container}>
            <Head>
                <title>Personel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                merhaba

            </main>
        </div>
    )
}